#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleProject
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr267_projecttask_cr267_probabilityofwin
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 265850000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Medium = 265850001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 265850002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr267_projecttask_cr267_status
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 265850000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 265850001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Incomplete = 265850002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr267_projecttask_cr267_team
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Global = 265850000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Local = 265850001,
	}
	
	/// <summary>
	/// Status of the Project task 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr267_projecttask_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Project task 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr267_projecttask_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cr267_projecttask")]
	public partial class cr267_Projecttask : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public cr267_Projecttask() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "cr267_projecttask";
		
		public const string EntityLogicalCollectionName = "cr267_projecttasks";
		
		public const string EntitySetName = "cr267_projecttasks";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_description")]
		public string cr267_Description
		{
			get
			{
				return this.GetAttributeValue<string>("cr267_description");
			}
			set
			{
				this.SetAttributeValue("cr267_description", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_duedate")]
		public System.Nullable<System.DateTime> cr267_Duedate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("cr267_duedate");
			}
			set
			{
				this.SetAttributeValue("cr267_duedate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_duedatefromparent")]
		public System.Nullable<System.DateTime> cr267_Duedatefromparent
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("cr267_duedatefromparent");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_isemailsent")]
		public System.Nullable<bool> cr267_Isemailsent
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cr267_isemailsent");
			}
			set
			{
				this.SetAttributeValue("cr267_isemailsent", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_probabilityofwin")]
		public virtual cr267_projecttask_cr267_probabilityofwin? cr267_Probabilityofwin
		{
			get
			{
				return ((cr267_projecttask_cr267_probabilityofwin?)(EntityOptionSetEnum.GetEnum(this, "cr267_probabilityofwin")));
			}
			set
			{
				this.SetAttributeValue("cr267_probabilityofwin", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_project")]
		public Microsoft.Xrm.Sdk.EntityReference cr267_Project
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cr267_project");
			}
			set
			{
				this.SetAttributeValue("cr267_project", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_projecttaskid")]
		public System.Nullable<System.Guid> cr267_ProjecttaskId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("cr267_projecttaskid");
			}
			set
			{
				this.SetAttributeValue("cr267_projecttaskid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_projecttaskid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.cr267_ProjecttaskId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_projectv2")]
		public Microsoft.Xrm.Sdk.EntityReference cr267_ProjectV2
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cr267_projectv2");
			}
			set
			{
				this.SetAttributeValue("cr267_projectv2", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_score")]
		public System.Nullable<int> cr267_Score
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("cr267_score");
			}
			set
			{
				this.SetAttributeValue("cr267_score", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_status")]
		public virtual cr267_projecttask_cr267_status? cr267_Status
		{
			get
			{
				return ((cr267_projecttask_cr267_status?)(EntityOptionSetEnum.GetEnum(this, "cr267_status")));
			}
			set
			{
				this.SetAttributeValue("cr267_status", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_taskname")]
		public string cr267_Taskname
		{
			get
			{
				return this.GetAttributeValue<string>("cr267_taskname");
			}
			set
			{
				this.SetAttributeValue("cr267_taskname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_team")]
		public virtual cr267_projecttask_cr267_team? cr267_Team
		{
			get
			{
				return ((cr267_projecttask_cr267_team?)(EntityOptionSetEnum.GetEnum(this, "cr267_team")));
			}
			set
			{
				this.SetAttributeValue("cr267_team", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_priority")]
		public System.Nullable<int> new_Priority
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_priority");
			}
			set
			{
				this.SetAttributeValue("new_priority", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_reasonforlessprobability")]
		public string new_Reasonforlessprobability
		{
			get
			{
				return this.GetAttributeValue<string>("new_reasonforlessprobability");
			}
			set
			{
				this.SetAttributeValue("new_reasonforlessprobability", value);
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Project task 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual cr267_projecttask_statecode? statecode
		{
			get
			{
				return ((cr267_projecttask_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Project task 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual cr267_projecttask_statuscode? statuscode
		{
			get
			{
				return ((cr267_projecttask_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 cr267_projecttask_ProjectV2_new_project
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr267_projectv2")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cr267_projecttask_ProjectV2_new_project")]
		public ExampleProject.new_Project cr267_projecttask_ProjectV2_new_project
		{
			get
			{
				return this.GetRelatedEntity<ExampleProject.new_Project>("cr267_projecttask_ProjectV2_new_project", null);
			}
			set
			{
				this.SetRelatedEntity<ExampleProject.new_Project>("cr267_projecttask_ProjectV2_new_project", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
